---
# Choose your timezone
timezone: Europe/Berlin
github_username: sujiba

# CIDR your nodes are on (e.g. 192.168.1.0/24)
node_cidr: 192.168.178.0/24
# The IP address to use with kube-vip, choose an available IP in your nodes network that is not being used
kube_vip_addr: 192.168.178.100

# Keep the next three options default unless you know what you are doing
cluster_cidr: 10.42.0.0/16
service_cidr: 10.43.0.0/16
coredns_addr: 10.43.0.10

# Below vars are for the xanmanning.k3s role
# ...see https://github.com/PyratLabs/ansible-role-k3s#globalcluster-variables

# (string) Use a specific version of k3s
k3s_release_version: "v1.28.2+k3s1"

# (bool) Install using hard links rather than symbolic links.
k3s_install_hard_links: true

# (bool) Escalate user privileges for all tasks
k3s_become: true

# (bool) Enable debug logging on the k3s service
k3s_debug: false

# (bool) Enable etcd embedded datastore
# Best practice for etcd is to define at least 3 members to ensure quorum is established
k3s_etcd_datastore: true

# (bool) Allow the use of unsupported configurations in k3s
# If you want to use 2 members or an even number of members, set to true
k3s_use_unsupported_config: true

# (string) Control Plane registration address
k3s_registration_address: "{{ kube_vip_addr }}"

# (list) A list of URLs to deploy on the primary control plane.
k3s_server_manifests_urls:
  # Kube-vip RBAC
  - url: https://raw.githubusercontent.com/kube-vip/kube-vip/main/docs/manifests/rbac.yaml
    filename: kube-vip-rbac.yaml
  # Essential Prometheus Operator CRDs (the rest are installed with the kube-prometheus-stack helm release)
  - url: https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.68.0/example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml
    filename: custom-prometheus-podmonitors.yaml
  - url: https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.68.0/example/prometheus-operator-crd/monitoring.coreos.com_prometheusrules.yaml
    filename: custom-prometheus-prometheusrules.yaml
  - url: https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.68.0/example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
    filename: custom-prometheus-scrapeconfigs.yaml
  - url: https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.68.0/example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
    filename: custom-prometheus-servicemonitors.yaml

# (list) A flat list of templates to deploy on the primary control plane.
# /var/lib/rancher/k3s/server/manifests
k3s_server_manifests_templates:
  - custom-coredns-helmchart.yaml.j2
  - custom-cilium-helmchart.yaml.j2
  - custom-cilium-l2.yaml.j2

# (list) A flat list of templates for installing static pod manifests on the control plane.
k3s_server_pod_manifests_templates:
  - kube-vip-static-pod.yaml.j2
