version: "3"

vars:
  KUBERNETES_DIR: "{{.ROOT_DIR}}/kubernetes"
  ANSIBLE_DIR: "{{.ROOT_DIR}}/ansible"

dotenv: [".config.env"]

env:
  KUBECONFIG: "{{.ROOT_DIR}}/kubeconfig"
  SOPS_AGE_KEY_FILE: ~/.config/sops/age/keys.txt

includes:
  ansible: .taskfiles/AnsibleTasks.yaml
  #cluster: .taskfiles/ClusterTasks.yaml
  precommit: .taskfiles/PrecommitTasks.yaml

tasks:
  init:
    desc: Initialize workstation dependencies with Brew
    cmds:
      - brew install {{.DEPS}} {{.CLI_ARGS}}
    preconditions:
      - sh: command -v brew
        msg: |
          Homebrew is not installed. Using MacOS, Linux or WSL?
          Head over to https://brew.sh to get up and running.
    vars:
      DEPS: >-
        age
        ansible
        ansible-lint
        cilium-cli
        direnv
        fluxcd/tap/flux
        go-task/tap/go-task
        helm
        ipcalc
        jq
        kubernetes-cli
        kustomize
        pre-commit
        prettier
        sops
        stern
        weaveworks/tap/gitops
        yamllint
        yq
