---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./bitnami.yaml
  - ./external-dns.yaml
  - ./ingress-nginx.yaml
  - ./intel.yaml
  - ./k8s-gateway.yaml
  - ./kubernetes-dashboard.yaml
  - ./metallb.yaml
  - ./metrics-server.yaml
  - ./rook-ceph.yaml
  - ./weave-gitops.yaml
