---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-longhorn
  namespace: flux-system
spec:
  path: ./kubernetes/apps/system/longhorn/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: longhorn
      namespace: system
  interval: 30m
  retryInterval: 1m
  timeout: 5m
