---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-homepage
  namespace: flux-system
spec:
  interval: 30m
  path: ./kubernetes/apps/selfhosted/homepage/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops
  wait: false
  dependsOn:
    - name: cluster-apps-longhorn
