---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: networking
spec:
  interval: 30m
  chart:
    spec:
      chart: external-dns
      version: 1.13.0
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    logLevel: info
    logFormat: text
    interval: 3m
    sources:
      - ingress
    policy: upsert-only
    registry: noop
    provider: pihole
    extraArgs:
      - --pihole-server=https://pihole-01.${SECRET_DOMAIN}
      - --pihole-password=${API_TOKEN}
