---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: networking
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: enabled
resources:
  - ./secret.sops.yaml
  - ./helmrelease.yaml
