---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: homepage
  namespace: selfhosted
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.0.3
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system

  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true

  values:
    # https://github.com/bjw-s/helm-charts/blob/main/charts/library/common/values.yaml
    controllers:
      main:
        type: statefulset
        strategy: rollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"

        statefulset:
          volumeClaimTemplates:
            - name: data
              accessMode: "ReadWriteOnce"
              size: 1Gi
              globalMounts:
                - path: /app

        containers:
          main:
            image:
              repository: ghcr.io/gethomepage/homepage
              tag: v0.7.3
              pullPolicy: IfNotPresent
            env:
              TZ: ${TIMEZONE}v
            resources:
              requests:
                cpu: 500m
                memory: 500Mi
              limits:
                memory: 1000Mi

    service:
      main:
        ports:
          http:
            port: 3000

    ingress:
      main:
        enabled: true
        ingressClassName: internal
        hosts:
          - host: &host "dashboard.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
