---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: netcup-webhook
  namespace: cert-manager
spec:
  interval: 15m
  chart:
    spec:
      chart: cert-manager-webhook-netcup
      version: 1.0.14
      sourceRef:
        kind: HelmRepository
        name: netcup-webhook
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    groupName: com.netcup.webhook

    certManager:
      namespace: cert-manager
      serviceAccountName: cert-manager

    image:
      repository: elvino76/cert-manager-webhook-netcup
      tag: 1.0.14
      pullPolicy: IfNotPresent

    service:
      type: ClusterIP
      port: 443

    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi