apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:SP6/Vyf7u1v6r/5R,iv:+hS+CBF2XD3+lGJKumsMVRNb4wWzx1A5HBEsbpMNXl8=,tag:Z6sQvkzvp/t3I3z0o0Ejeg==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:5uW6iUP53WwygtBxLxbf27MySI84MQ==,iv:tLgPQrnLO853oYqMOFz51GaP8v+4pWb5PIPVJ9wL9Vk=,tag:qBT460qUbPW7Pmx9lcOVPQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19sq2gjylpmkr7dyrhtgnvl904t382wgdx824kts3e6p28a4yhe4q8jtewp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBidXVOTzlxVjBMVjd4bmxM
            TFhPU3lab0N3QlFQQnJIa2hGRGNmN3VoZnd3CmQ2L016U2ViNlY0a29RUVNINVNr
            S2lVUnJSbldMa1hqSTA2b2huanpOWk0KLS0tIFUvNWI0cVIyUUZ0QlVQTHZsOHF2
            TkhydnR3aHNRNzgzQ2ZCVGpzUkhXbHcKwD4EZP41OSLwJE865vYHufFw38MYq7PL
            918JykOIM2pbqWagNLBrluUHu3zxklVfqEh3MjR8pWsx0f/3+BLxkw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-08T20:54:35Z"
    mac: ENC[AES256_GCM,data:IU4fPtIVKzvMJVcUj2cwliZNR2ZE6oR8GisQmvCRyO6Ae1LqeONR43RWXaeBDKyYLmKoiV870R7nN6NvVgT6l8WJNpHGqjdh44esO4rxD528EyGrinJxHRd2lVpCU10b7YplShyMVyUXP5uNU4tSv8p5t8K4K3/yFb6gFtLJ2HQ=,iv:i5/9MaX1hulxOhkjbr9rOq4uozWIiyYIAPp8KBhY41Q=,tag:QSDl+D5KyZUFwpTEs5rTEg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
