---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "Europe/Berlin"
  KUBE_VIP_ADDR: "192.168.178.8"
  METALLB_LB_RANGE: "192.168.178.220-192.168.178.230"
  METALLB_K8S_GATEWAY_ADDR: "192.168.178.220"
  METALLB_INGRESS_ADDR: "192.168.178.221"
