---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-cert-manager
  namespace: flux-system
spec:
  path: ./kubernetes/apps/certificates/cert-manager/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-cert-manager-issuers
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-cert-manager
    - name: cluster-apps-cert-manager-webhook
  path: ./kubernetes/apps/certificates/cert-manager/issuers
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-cert-manager-webhook
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-cert-manager
  path: ./kubernetes/apps/certificates/cert-manager/webhook
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
