---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: uptime-kuma
  namespace: selfhosted
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.0.3
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system

  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true

  values:
    controllers:
      main:
        type: deployment
        strategy: Recreate
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          main:
            image:
              repository: louislam/uptime-kuma
              tag: 1.23.3
            resources:
              requests:
                cpu: 500m
                memory: 500Mi
              limits:
                memory: 1000Mi

    service:
      main:
        ports:
          http:
            port: 3001

    ingress:
      main:
        enabled: true
        ingressClassName: internal
        hosts:
          - host: &host "uptime.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
        type: local-hostpath
        size: 1Gi
